variable "project_name"      { type = string }
variable "instance_type"     { type = string }
variable "key_name"          { type = string }
variable "security_group_id" { type = string }
variable "subnet_id"         { type = string }
variable "ami_id"            { type = string }
variable "blue_app_version"  { type = string }
variable "green_app_version" { type = string }
variable "dockerhub_username"{ type = string }
